#!/usr/bin/env python3
"""
reporter.py
Automated Report Generation Module
Contains: ReportGenerator
"""

import os
import datetime
import json
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side


class ReportGenerator:
    """Generate formatted Excel reports from scan results."""

    def __init__(self):
        self.report_dir = "data/reports"
        os.makedirs(self.report_dir, exist_ok=True)

    def generate_excel(self, title, mode="Demo Data"):
        """
        Create an Excel report.
        :param title: Report title
        :param mode: "Demo Data" or "Auto-Collect from Modules"
        :return: Path to generated Excel file
        """
        wb = Workbook()
        ws = wb.active
        ws.title = "Scan Results"

        # Styles
        header_font = Font(name="Calibri", size=14, bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
        header_align = Alignment(horizontal="center", vertical="center")
        thin_border = Border(
            left=Side(style="thin"), right=Side(style="thin"),
            top=Side(style="thin"), bottom=Side(style="thin")
        )

        # Title row
        ws.merge_cells("A1:D1")
        ws["A1"] = title
        ws["A1"].font = header_font
        ws["A1"].fill = header_fill
        ws["A1"].alignment = header_align
        ws.row_dimensions[1].height = 30

        # Metadata
        ws["A3"] = "Generated On:"
        ws["B3"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ws["A4"] = "Tool:"
        ws["B4"] = "Automated Security & Monitoring Toolkit"
        ws["A5"] = "Mode:"
        ws["B5"] = mode

        # Headers
        headers = ["#", "Test Type", "Target", "Result/Status", "Details"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=7, column=col, value=header)
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
            cell.alignment = Alignment(horizontal="center")
            cell.border = thin_border

        # Data based on mode
        if mode == "Auto-Collect from Modules":
            data_rows = self._collect_from_modules()
        else:
            data_rows = self._get_demo_data()

        # Fill data
        for r_idx, row_data in enumerate(data_rows, 8):
            for c_idx, value in enumerate(row_data, 1):
                cell = ws.cell(row=r_idx, column=c_idx, value=value)
                cell.border = thin_border
                cell.alignment = Alignment(vertical="top", wrap_text=True)

        # Adjust column widths
        ws.column_dimensions["A"].width = 6
        ws.column_dimensions["B"].width = 20
        ws.column_dimensions["C"].width = 28
        ws.column_dimensions["D"].width = 22
        ws.column_dimensions["E"].width = 45

        # Summary sheet
        ws2 = wb.create_sheet(title="Summary")
        ws2["A1"] = "Executive Summary"
        ws2["A1"].font = Font(size=16, bold=True)
        ws2["A3"] = "Total Tests Conducted:"
        ws2["B3"] = len(data_rows)
        ws2["A4"] = "High Risk Findings:"
        ws2["B4"] = sum(1 for r in data_rows if "vulnerable" in str(r[4]).lower() or "open" in str(r[4]).lower() or "cracked" in str(r[4]).lower())
        ws2["A5"] = "Report Generated By:"
        ws2["B5"] = "Automated Security Toolkit"
        ws2["A6"] = "Report Mode:"
        ws2["B6"] = mode

        # Save
        filename = f"report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        filepath = os.path.join(self.report_dir, filename)
        wb.save(filepath)
        return filepath

    def _get_demo_data(self):
        """Return demo data rows."""
        return [
            [1, "Port Scan", "192.168.1.1", "Completed", "Ports 80, 443 open | 21, 22 closed"],
            [2, "SQLi Test", "testsite.com/login.php", "Safe", "No SQL error signatures detected in 10 payloads"],
            [3, "Subdomain Enum", "example.com", "Completed", "Found 3 active subdomains: www, mail, ftp"],
            [4, "Password Check", "user_input", "Strong", "SHA-256 hash generated | Length: 12+ chars"],
            [5, "File Encrypt", "secret.txt", "Success", "Fernet encryption applied | Key saved securely"],
            [6, "Monitoring", "Local System", "Completed", "10 screenshots captured over 60 seconds"],
        ]

    def _collect_from_modules(self):
        """Try to collect real data from module output files."""
        data_rows = []
        idx = 1

        # Check for scan logs
        log_files = {
            "data/activity_log.txt": "System Monitoring",
            "data/crypto/password_hashes.txt": "Password Generation",
            "data/crypto/last_key.txt": "File Encryption",
        }

        for log_path, test_type in log_files.items():
            if os.path.exists(log_path):
                try:
                    with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                        lines = f.readlines()
                    if lines:
                        detail = lines[-1].strip() if lines else "No entries"
                        data_rows.append([idx, test_type, "Local System", "Completed", detail[:200]])
                        idx += 1
                except Exception:
                    pass

        if not data_rows:
            # Fallback to demo if no logs found
            data_rows = self._get_demo_data()

        return data_rows
