#!/usr/bin/env python3
"""
reporter.py
Automated Report Generation Module
Contains: ReportGenerator
"""

import os
import datetime
import json
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side


class ReportGenerator:
    """Generate formatted Excel reports from scan results."""

    def __init__(self):
        self.report_dir = "data/reports"
        os.makedirs(self.report_dir, exist_ok=True)

    def generate_excel(self, title, scan_file=None):
        """
        Create an Excel report.
        :param title: Report title
        :param scan_file: Optional path to scan results file (txt/json)
        :return: Path to generated Excel file
        """
        wb = Workbook()
        ws = wb.active
        ws.title = "Scan Results"

        # Styles
        header_font = Font(name="Calibri", size=14, bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
        header_align = Alignment(horizontal="center", vertical="center")
        thin_border = Border(
            left=Side(style="thin"), right=Side(style="thin"),
            top=Side(style="thin"), bottom=Side(style="thin")
        )

        # Title row
        ws.merge_cells("A1:D1")
        ws["A1"] = title
        ws["A1"].font = header_font
        ws["A1"].fill = header_fill
        ws["A1"].alignment = header_align
        ws.row_dimensions[1].height = 30

        # Metadata
        ws["A3"] = "Generated On:"
        ws["B3"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ws["A4"] = "Tool:"
        ws["B4"] = "Automated Security & Monitoring Toolkit"

        # Headers
        headers = ["#", "Test Type", "Target", "Result/Status", "Details"]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=6, column=col, value=header)
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
            cell.alignment = Alignment(horizontal="center")
            cell.border = thin_border

        # Parse scan file if provided
        data_rows = []
        if scan_file and os.path.exists(scan_file):
            ext = os.path.splitext(scan_file)[1].lower()
            if ext == ".json":
                with open(scan_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    for idx, item in enumerate(data, 1):
                        data_rows.append([
                            idx,
                            item.get("type", "N/A"),
                            item.get("target", "N/A"),
                            item.get("status", "N/A"),
                            item.get("details", "")
                        ])
            else:
                # Plain text - parse simple format
                with open(scan_file, "r", encoding="utf-8") as f:
                    lines = f.readlines()
                    for idx, line in enumerate(lines, 1):
                        line = line.strip()
                        if line:
                            data_rows.append([idx, "Scan", "N/A", "Info", line])
        else:
            # Demo data if no file provided
            data_rows = [
                [1, "Port Scan", "192.168.1.1", "Completed", "Ports 80, 443 open"],
                [2, "SQLi Test", "testsite.com", "Safe", "No vulnerabilities found"],
                [3, "Subdomain", "example.com", "Completed", "Found 3 active subdomains"],
            ]

        # Fill data
        for r_idx, row_data in enumerate(data_rows, 7):
            for c_idx, value in enumerate(row_data, 1):
                cell = ws.cell(row=r_idx, column=c_idx, value=value)
                cell.border = thin_border
                cell.alignment = Alignment(vertical="top", wrap_text=True)

        # Adjust column widths
        ws.column_dimensions["A"].width = 6
        ws.column_dimensions["B"].width = 18
        ws.column_dimensions["C"].width = 25
        ws.column_dimensions["D"].width = 20
        ws.column_dimensions["E"].width = 40

        # Summary sheet
        ws2 = wb.create_sheet(title="Summary")
        ws2["A1"] = "Executive Summary"
        ws2["A1"].font = Font(size=16, bold=True)
        ws2["A3"] = "Total Tests Conducted:"
        ws2["B3"] = len(data_rows)
        ws2["A4"] = "High Risk Findings:"
        ws2["B4"] = sum(1 for r in data_rows if "vulnerable" in str(r[4]).lower() or "open" in str(r[4]).lower())
        ws2["A5"] = "Report Generated By:"
        ws2["B5"] = "Automated Security Toolkit"

        # Save
        filename = f"report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        filepath = os.path.join(self.report_dir, filename)
        wb.save(filepath)
        return filepath
